zooniverse/mobile

- ProjectList.js
- android/app/src/main/AndroidManifest.xml
Add network detection and an error in case a network connection loss is detected.
Probably the easiest way to test this is in the iOS simulator is by turning off your computer's wi-fi, in android you have to go into settings and turn cellular off.
Also converts ProjectList from class to react component
Closes #11
> Add network detection and error for iOS and Android

- .gitignore
- android/app/build.gradle
- android/build.gradle
Adds config updates to enable generating the android apk.
https://facebook.github.io/react-native/docs/signed-apk-android.html
(keystore isn't checked in, anyone else wishing to run this will need they keystore, I can supply)
> Add configs for android build (generating the apk)

- index.android.js
Make sure the tracking for Android mimics the tracking for iOS
> Google analytics - change screen tracking to Event (on Android)

- index.ios.js
- package.json
- src/components/NavBar.js
- src/components/ProjectDisciplines.js
- src/components/SideDrawer.js
- src/components/SideDrawerContent.js
- src/components/StyledText.js
- src/containers/app.js
Closes #35 
Adds a new side drawer component:
*  Added to router
*  Added placeholder links (About and Publications just go Home for now)
*  Added links to social media
*  Also moved the Signout link currently on the home page to the side drawer
*  Adds status bar opaque teal for iOS to display on top
> Add and style side drawer

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
Removes unnecessary Android permissions being automatically added by RN.
Changes SYSTEM_ALERT_WINDOW to only display in debug mode
Removes BLUETOOTH, READ_EXTERNAL_STORAGE and READ_PHONE_STATE 
You can check the permission changes either through the device or emulators settings, or by following the instructions here (requires an apk and adb in your path):  http://stackoverflow.com/questions/21091022/listing-permissions-of-android-application-via-adb
Fixes #47
> Fix android permissions

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
Based on feedback for PR #57 - I just renamed the variable from excludeSystemAlertWindowPermission to shouldRemoveSystemAlertWindowPermission (it needs to have that true/false values preserved, I could negate it but that also makes it less readable imo).
I think this improves the understandability of what it's doing.  (if you have any other ideas I'm good with that too - thanks!)
> Rename variable for readability

- src/components/NavBar.js
- src/components/SideDrawerContent.js
- src/components/SignIn.js
The following touch elements have a rather small tappable area so to make it easier to tap I've increased the padding on the following items:
*  Side menu open (in nav bar)
*  Back arrow (in nav bar)
*  Social icons (in side menu)
*  Links (in side menu)
*  Forgot password link (on sign in)
> Make tappable area larger for touch elements

- src/actions/index.js
- src/components/Discipline.js
- src/components/ProjectDisciplines.js
- src/components/ProjectList.js
- src/containers/app.js
Fixes #60 
When quickly navigating around, the router is not always doing component unmounts/mounts (https://github.com/aksonov/react-native-router-flux/issues/415) and so the project list isn't properly refreshing
This PR moves more of the logic for filtering project lists into redux, and fetches once on application mount, then just filters the list displayed once a discipline is chosen (rather than an API call each time the component is mounted)
> Refactor project list display a bit

- ios/ZooniverseMobile/AppDelegate.m
- src/components/NavBar.js
Two landscape fixes:
*  Use flex to center avatar
*  Status bar is by default hidden in landscape mode in iOS - this adds it back
Fixes #68
> Fix landscape issues - user avatar positioning and status bar disappearing

- src/components/SignIn.js
Adds a ScrollView container to the sign in page to allow scrolling in case the screen is too small to show the entire sign in page. 
Also adds a top padding calculation to take into account iOS (with the status bar) or Android.
Fixes #70
> Add scrolling to sign in

- src/actions/index.js
- src/containers/app.js
Fixes #65 
When an app state changes to 'active', this will reload user avatar data (eventually this will be used to reload other data, such as project preferences).  This app state listener will fire when users press the home button and then reopens the app later (state changes from background to active)
This PR also refactors code a bit to rely more heavily on promises, which will make adding project preferences and stats easier later.
> Add check on app state change to reload user data

- README.md
- android/app/build.gradle
- android/app/google-services.json
- android/app/src/release/google-services.json
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/AppDelegate.m
- ios/ZooniverseMobile/Info.plist
In order to have a separate API key for push notifications in both dev and prod, we need to have a separate firebase project for development only, which is set up by google-services.json config files.  Then we can have the release version kept separately from the dev version, per the following document:  https://developers.google.com/android/guides/google-services-plugin
This PR moves the current google-services.json from app/ into app/src/release/ and adds a new google-services.json for the new ZooniverseMobileDev Firebase project.  It also adds a new PUSHER_API_KEY for dev. (You'll need to add a PUSHER_API_KEY_DEV to ~/.gradle/gradle.properties - I can give you the value).  It also adds the new Pusher API Key for dev on iOS.
Fixes #79
> Updates to allow for dev version of Push notifications

- android/app/build.gradle
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/Info.plist
- package.json
- src/components/NavBar.js
- src/components/Project.js
- src/components/ZooWebView.js
- src/containers/app.js
- src/reducers/index.js
Adds a Webview component for viewing PFE projects within Webview instead of going outside the app to the default browser.  For non-PFE projects it still opens in the browser.
Since page loads within PFE are mostly from ajax requests, natively they're not processed as new page hits, and thus the router wasn't capturing them all to populate the action stack.  This made the back button not work when navigating between pages.  This also adds logic for custom back handling by adding event listeners to "a" links that fired a message over a bridge to notify the app that a link has been clicked.
> Add webview view for PFE projects

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/zooniversemobile/MainActivity.java
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/AppDelegate.m
- ios/ZooniverseMobile/Info.plist
- package.json
- src/actions/index.js
- src/components/Button.js
- src/components/NotificationModal.js
- src/components/StyledModal.js
- src/components/StyledText.js
- src/components/__tests__/__snapshots__/Input-test.js.snap
- src/components/__tests__/__snapshots__/PublicationFilter-test.js.snap
- src/components/__tests__/__snapshots__/PublicationList-test.js.snap
- src/components/__tests__/__snapshots__/Register-test.js.snap
- src/components/__tests__/__snapshots__/SignIn-test.js.snap
- src/components/__tests__/__snapshots__/StyledText-test.js.snap
- src/containers/zooniverseApp.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
- src/theme.js
*  Adds support to handle project_id in push notification payload
*  Uses PushNotificationIOS from react-native for iOS and react-native-fcm for android/firebase
*  On Android, when app is in foreground, sends a local notification to display in the system tray
*  When project ID is present and one that is listed in the Mobile-Friendly projects) it will directly open that project in the browser
Fixes #72
> Open project directly from project-specific push notification

- android/app/src/main/java/com/zooniversemobile/MainActivity.java
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/app/src/main/java/com/zooniversemobile/MainApplicationPackage.java
- android/app/src/main/java/com/zooniversemobile/NotificationSettings.java
- android/app/src/main/java/com/zooniversemobile/PusherProperty.java
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/NotificationSettings.h
- ios/ZooniverseMobile/NotificationSettings.m
- src/actions/auth.js
- src/actions/index.js
- src/actions/user.js
- src/components/NotificationSettings.js
- src/components/ProjectNotification.js
- src/components/SideDrawerContent.js
- src/components/__tests__/NotificationSettings-test.js
- src/components/__tests__/ProjectNotification-test.js
- src/components/__tests__/__snapshots__/NotificationSettings-test.js.snap
- src/components/__tests__/__snapshots__/ProjectNotification-test.js.snap
- src/components/__tests__/__snapshots__/SideDrawerContent-test.js.snap
- src/containers/app.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
Adds the Notification Settings screen (on the side menu) to allow users to subscribe or unsubscribe to General Zooniverse Notifications or specific projects (populated from the list of Mobile-Friendly Projects).
Note that the notification settings are saved at the device level, since the list of projects are based on the Mobile friendly projects (and not the user preferences), and also notifications subscriptions are stored at the device level with Pusher.
*  Add support in android and ios for updating interest subscriptions in pusher (pusher doesn't have a react-native library, only native libraries)
*  Use NativeModules (RN) to send message from RN to Native to update the Pusher "interest" subscriptions when checked/unchecked
*  For iOS, if push isn't enabled, display a message …
> Add notifications settings screen

- android/app/src/main/AndroidManifest.xml
Currently Android is showing "ZooniverseMobile" (the project name) as the app name to the user.  This updates that label so it simply says  "Zooniverse".
> Update Android App Display Name

- ios/ZooniverseMobile/AppDelegate.m
- src/components/ProjectDisciplines.js
- src/containers/zooniverseApp.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
Since once iOS prompts users for push notifications only once, and by default on application load, it can be a better experience and less jarring to move the permissions until later, and also to explain what notifications will be used for before prompting.
This PR:
*  Moves to use RN's PushNotificationIOS so that the timing of the prompt is controlled on the react-native side
*  Also uses RN alert to give the explanation and store within redux whether the user has been prompted, so it doesn't re-prompt.  (As it works currently we can't re-ask a user to enable notifications - but this way we can if they decide later they would like to enable them)
> Add Permissions Primer

- src/actions/index.js
- src/components/ProjectDisciplines.js
- src/components/ProjectList.js
- src/components/PublicationList.js
- src/components/SignIn.js
- src/components/UserAvatar.js
- src/components/__tests__/ProjectDiscipline-test.js
- src/components/__tests__/ProjectList-test.js
- src/components/__tests__/__snapshots__/ProjectDiscipline-test.js.snap
- src/components/__tests__/__snapshots__/UserAvatar-test.js.snap
- src/containers/app.js
- src/reducers/index.js
Fixes #42 
*  Remove the in-component Offline messaging to instead just display an error message when the user goes offline (this seems more consistent with how other apps handle offline messaging - such as CNN, Target, etc. and also simplifies component code)
*  Store project list in local storage to fall back on in case of slow or no internet connection, rather than making it vanish altogether
*  Default the avatar image source in case the user is offline and we can't download the avatar image from the server
*  Update tests
> Changes to offline handling

- package.json
- src/components/__tests__/__snapshots__/OverlaySpinner-test.js.snap
Add babel-eslint to dev dependencies, the atom linter is broken without it.
> Add babel-eslint

- __mocks__/crypto-js.js
- package.json
- src/actions/session.js
- src/components/__tests__/__snapshots__/OverlaySpinner-test.js.snap
- src/containers/app.js
- src/utils/__tests__/utils-test.js
- src/utils/session.js
Implements session generation for storing with classification data in the same manor as PFE.
> Add crypto-js, session generator

- package.json
Recently panoptes-client added using window.location:
https://github.com/zooniverse/panoptes-javascript-client/blob/master/lib/config.js#L63
which is causing an issue in mobile due to there being no window object since it's not a browser.  This fixes the version at 2.5.2 until a fix is in place.
> Fix at older version of panoptes-client

- ios/ZooniverseMobile.xcodeproj/project.pbxproj
Today the native animated library stopped being automatically linked.  Likely as a result of a package update but I wasn't able to locate the culprit.  This manually links the library in xcode.
> Manually link Native Animated Library

- android/app/src/main/java/com/zooniversemobile/MainActivity.java
- src/containers/zooniverseApp.js
Fixes a few issues in Android (identified by Laura) and that I noticed on iOS while testing that fix
*  Fix so that Android doesn't send a notification when onMessageReceived unless it has a Notification.  I believe this is happening because pusher is sending a registration success message.  Currently this crashes android upon initial install. [Fixes #67]
*  Fix so that Android and iOS < 10 doesn't erroneously display an empty message on registration success
*  Fix iOS so that the interests are synced upon push notification registration.  This is to avoid a  race condition where the interests are synced prior to being prompted for registration, so that if a push notification is sent at the first install (and before any re-syncing occurs) the push notification won't go through.
> Fix push issues in ios and android

- src/actions/index.js
There was a typo where the item retrieved from local storage was called projects where it should've been projectList.  This was causing the project list to not be retrieved immediately from local storage, as intended.
> Fix typo in saving project store

- src/actions/index.js
- src/actions/user.js
Project data is stored locally (in case a user has a slow / no internet connection), this adds functionality to store the workflow data as well, which is used to indicate that a project is mobile friendly and displays the mobile icon.  This way in case the api sync hasn't completed before the user visits a category it won't be jumpy or incorrectly go to the PFE project.
(it's probably easiest for comparison to merge #109 first, but I had to incorporate that to get it running in iOS)
> Store workflow data

- package.json
Since the fix for panoptes-client went in that no longer relies on window we can reinstate the panoptes client to use the most recent.
[Fixes #106]
> Allow panoptes client to be most recent version

- src/actions/auth.js
- src/actions/user.js
Fixes an issue where users that can't auth will receive an error.  (this appears to just happen in dev when switching environments).  Rather than displaying an error this will redirect to the sign in page if the user isn't logged in.
> Fix user auth error

- package.json
- src/actions/classifier.js
- src/components/ClassificationPanel.js
- src/components/OverlaySpinner.js
- src/components/Project.js
- src/components/Question.js
- src/components/StyledMarkdown.js
- src/components/SwipeClassifier.js
- src/components/__tests__/ClassificationPanel-test.js
- src/components/__tests__/Question-test.js
- src/components/__tests__/StyledMarkdown-test.js
- src/components/__tests__/SwipeClassifier-test.js
- src/components/__tests__/__snapshots__/ClassificationPanel-test.js.snap
- src/components/__tests__/__snapshots__/Question-test.js.snap
- src/components/__tests__/__snapshots__/StyledMarkdown-test.js.snap
- src/components/__tests__/__snapshots__/SwipeClassifier-test.js.snap
- src/containers/app.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
- src/theme.js
- src/utils/default-md-html.js
- src/utils/remove-md-tab.js
In an attempt to make this PR smaller I've pulled out the presentational base of the swipe app.  This doesn't include the Tutorial, Guide or subject swipe (those will be in later PRs)
Adds markdown support which is used in multiple places in the classifier (the question, field guide, tutorial).   I attempted several react-native markdown libraries but none were close enough or customizable enough to the markdownz rendering - and so I settled for using a combination of webview and the markdown-it library
*  default-md-html.js used as a basic html template for all markdown being rendered using webview.  It includes a method to set the height because webview requires an explicit height, but we don't know the height until the markdown has been rendered.
*  remove-md-tab.js is a plugin for …
> Add Classification Panel for Swipe

- src/components/SwipeClassifier.js
Fixes #119 
After merging the classifier PR my solution no longer was feasible.  This will prevent navigation errors when moving from one project to another by displaying the spinner until the workflow has been loaded.
> Fix navigation errors

- package.json
- src/components/FullScreenImage.js
- src/components/SwipeClassifier.js
- src/components/Swipeable.js
- src/components/ZoomableImage.js
- src/components/__tests__/FullScreenImage-test.js
- src/components/__tests__/SwipeClassifier-test.js
- src/components/__tests__/ZoomableImage-test.js
- src/components/__tests__/__snapshots__/FullScreenImage-test.js.snap
- src/components/__tests__/__snapshots__/SwipeClassifier-test.js.snap
- src/components/__tests__/__snapshots__/Swipeable-test.js.snap
- src/components/__tests__/__snapshots__/ZoomableImage-test.js.snap
Adds the ability to tap an image in the classifier and see it displayed full screen.  If the pan and zoom is enabled on the workflow, it will allow the user to pinch to zoom.
*  Also adds new npm package for creating zoomable images
*  The ZoomableImage component can be reuseable elsewhere if desired
> Add ability to view the subject full screen and zoom if available

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/AppDelegate.m
- ios/ZooniverseMobile/Info.plist
- package.json
Add restriction to iOS and Android to allow portrait mode only, since the swipe projects will need to be displayed in portrait and we have to set allowable mode at the app level.
> Set to allow portrait only

- src/actions/classifier.js
- src/actions/index.js
- src/components/SwipeClassifier.js
- src/components/Swipeable.js
- src/components/UnlinkedTask.js
- src/components/__tests__/__snapshots__/Swipeable-test.js.snap
- src/reducers/index.js
Add Unlinked Tasks/Shortcuts and ability to save additional annotations for the unlinked task and the ability to remove annotations in case a the switch is "unchecked".  This will allow more than two unlinked tasks, but other checks should prevent a workflow with more than two from being swipe eligible, due to screen size.
> Add Unlinked Tasks

- src/components/UnlinkedTask.js
There's an issue with the way unlinked tasks/shortcuts are displayed in the mobile app (see images attached). This clears up the issue and should be merged in order to be live by the Dec. 13 launch of Floating Forests (with a couple days needed for Apple to approve the update).
Changed styles for the UnlinkedTask component.
> Restyle UnlinkedTask Component

- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/actions/index.js
- Only show `launch_approved: true` projects to ensure all mobile projects are in fact mobile ready and verified by the team.
- Fix some file structure issues with the xcode project file caused from updating from xcode 8 to 9.
- Remove duplicate listing of `panoptes-client` in `package.json`
- Committing `package-lock.json` per https://docs.npmjs.com/files/package-lock.json
> Display mobile projects

- src/actions/index.js
Fixes #151.
Instead of pulling the top 100 projects from a page, we are pulling only the ones that are `mobile_friendly`.
> Issue151 - Use mobile_friendly workflow attribute

- src/components/About.js
- src/components/ClassificationPanel.js
- src/components/NavBar.js
- src/components/ProjectDisciplines.js
- src/components/ProjectList.js
- src/components/PublicationFilter.js
- src/components/PublicationList.js
- src/components/Register.js
- src/components/Settings.js
- src/components/SignIn.js
- src/components/Swipeable.js
- src/components/Tutorial.js
- src/components/ZooWebView.js
- src/components/__tests__/__snapshots__/NavBar-test.js.snap
This is a bug fix for issue #144. Basically whenever a header title was long it would overlap the other header buttons and basically trap the user on the page because the text would block the buttons.
I refactored the nav bar code to use relative positioning instead of absolute positioning and I noticed that all of the pages on the app had a `topPadding` set to the size of the header. So that is why I have touched so many files in this PR.
> 144: Fix Header

- src/components/SwipeSubject.js
- src/components/Swipeable.js
- src/components/ZoomableImage.js
- src/components/__tests__/__snapshots__/SwipeSubject-test.js.snap
- src/components/__tests__/__snapshots__/Swipeable-test.js.snap
- src/components/__tests__/__snapshots__/ZoomableImage-test.js.snap
Fixing some issues caused by  #159.
Namely that I was not correctly implementing the automatic resizing provided in react. Before this code change, the images were being cropped to be a specific size, now they are actually scaled down.
Unfortunately, we still have to use `Image.getSize` to calculate the size of the overlay view. However, now if that function fails, we still see the image, the overlay view will just be a little to big.
We have to use this function because React Native doesn't provide any way to know the size of an automatically resized image.
> Fix image cropping

- android/app/build.gradle
Fixes #196
Google is forcing an Android SDK update.
WARNING: 
You will have to download the SDK 27. You can do this through the Android Studio SDK Manager. You will also have to download the SDK Android Build Tools version 27.0.3.
> Update Android Target Version

- android/app/src/main/AndroidManifest.xml
Fixes a bug where two icons show on Android.
Testing:
Installing the Android app on a simulator or device will only show one icon.
> Update Android Manifest

- __mocks__/react-native-swiper.js
- package-lock.json
- package.json
- src/actions/images.js
- src/components/classifier/ClassificationPanel.js
- src/components/classifier/SwipeClassifier.js
- src/components/classifier/SwipeTabs.js
- src/components/classifier/Tutorial.js
- src/components/classifier/TutorialStep.js
- src/components/classifier/__tests__/__snapshots__/Tutorial-test.js.snap
- src/components/common/FittedImage.js
Fixes #217 
Refactored how the tutorial is displayed. It is now displayed as a paginating scroll view. Appearance-wise it looks identical, but it fixes a visual issue where the image load lags behind the markdown load.
Using a paginating scrollview, all of the content loads at once. This means the transition is smooth between pages.
Also, fix a bug that caused a crash with image caching.
> Fix Tutorial View

- __mocks__/react-native-device-info.js
- android/app/build.gradle
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/actions/classifier.js
- src/components/Markings/DrawingClassifier.js
- src/components/Markings/DrawingClassifierSubject.js
- src/components/Markings/DrawingModal.js
- src/components/Markings/components/DrawingButton.js
- src/components/Markings/components/DrawingButtons.js
- src/components/Markings/components/DrawingToolView.js
- src/components/Markings/components/InstructionView.js
- src/components/Markings/components/MarkableImage.js
- src/components/Markings/components/ShapeInstructionsView.js
- src/components/Markings/components/SvgOverlay.js
- src/components/classifier/ClassificationPanel.js
- src/components/classifier/ClassifierButton.js
- src/components/classifier/NeedHelpButton.js
- src/components/classifier/Question.js
- src/components/classifier/Tutorial.js
- src/components/classifier/TutorialStep.js
- src/components/classifier/__tests__/__snapshots__/ClassificationPanel-test.js.snap
- src/components/classifier/__tests__/__snapshots__/Question-test.js.snap
- src/components/classifier/__tests__/__snapshots__/Tutorial-test.js.snap
There are a few things going on here:
1) Dynamicaly Size Text for Android
- Add `react-native-device-info` this package lets us check if the device is a tabler
- Add Dynamic sizing for text in the classifier and tutorial
2) Remove drawing modal for tablet
- We removed the modal because we don't need to create additional space on tablet.
3) Various layout and formatting fixes
- Fixed an issue with tutorial margins
- Fixed a bug where the field guide always show on the drawing task
> Add tablet specific code/Assorted refactors

- src/utils/imageUtils.js
Fixes bug noted [here](https://www.zooniverse.org/talk/739/910315?comment=1509585&page=1)
The changes are pretty simple: 
The code was assuming that between the last period and the end of an image url would be the extension like so: 
`https://www.imagehost.image.jpeg`
However, the code fails if the image url has parameters.
`https://www.imagehost.image.jpeg?height=256;width=256`.
So the new code change just scrubs out the parameters
> Just grab the file type, no parameters

- src/actions/projects.js
- src/components/classifier/MultiAnswerClassifier.js
- src/components/classifier/QuestionClassifier.js
- src/constants/PageKeys.js
- src/containers/app.js
- src/navigators/classifierNavigator.js
- src/utils/workflow-utils.js
+ Switch task type assignment to key off the API value rather than the number of answers in the task.
+ BEFORE MERGING: Chelsea will remove TODOs in projects.js. These TODOs allow work on this feature to continue while the panoptes frontend still classifies multi answer workflows as not mobile_friendly.
This PR allows us to include projects in the mobile app that ask users to select multiple answers from a list of answers. There are two test projects in Preview: one that allows you to check multi answer, and one to allow you to check that single answer still works. @mcbouslog and I verified together that the call to the backend works correctly - yay!
I can make the "BEFORE MERGING" changes described above and release this whenever, but multi-answer projects will only start to show up on …
> Navigate to separate components for single and multiple answer questions

- README.md
- metro.config.js
- package-lock.json
- package.json
This PR takes care of a few issues. It removes the need to manually delete the `react-native` package from the `react-native-deck-swiper` node_modules and updates the Readme accordingly. It also fixes the issues we were having with `npm run android` running into `react-native-vector-icons` issues.
> Blacklist Items

- android/app/build.gradle
- android/build.gradle
- src/actions/projects.js
Turns out when we approve a project for launch, it stays beta approved, too. So projects that did both beta and launch were showing up twice in the app. We have tweaked the filters to prevent that.
Reviewers:
1. Thank you for all your help!
2. To ensure that this works, please verify that on your device (pointed at production) the following projects show up exactly once (not twice, not zero times):
- Bash the Bug: fighting antibiotic resistance 
- Camera CATalogue: analyzing wildlife photos to help Panthera protect big cats
- Euclid Challenge the Machines: identifying simulated gravitational lenses 
- Floating Forest: mapping change across the world’s giant kelp forests 
- Galaxy Zoo: separating smooth galaxies from those with features 
- Grouse Grooves: helping to conserve the greater …
> Double Project Issue

- src/utils/workflow-utils.js
Fixes #278  .
This PR allows a workflow with a flipbook to be enabled in the app. Read more on the issue above. With the introduction of multi-image subjects, it shouldn't be an issue having a workflow with a flipbook in the app.
> Allow Flipbook

- package-lock.json
- src/actions/__tests__/projects-test.js
- src/actions/projects.js
Fixes #303 
- Optimize the way we set museum mode. Instead of a call for all `project_roles` on every project in the mobile app, we make a single call for all projects where the current user has the `museum` role, but only if logged in.
- For those projects with the museum role, the `in_museum_mode` flag is triggered if they are in the app.
When reviewing, you can test this out with the Project With All Mobile Workflow Types, which I've promoted to Beta Review and should be available to both logged in and anonymous users.
> Only Mark Museum Mode if User Has Role

- src/components/Markings/DrawingClassifier.js
Children can mash the submit button all they want, but it disables after the first press until a new image loads
+ I also checked whether other workflows have this problem. I was not able to reproduce the issue in the other workflows.
Fixes https://github.com/zooniverse/mobile/issues/310.
> Fix Museum Mode Fast Tap Issue (appears to be specific to drawing workflow)

- src/constants/globals.js
Fixes #292 
The social sciences icon was not looking for the correct key value. The `GLYPHMAP` was using `'social-science'` instead of `'social science'`
> Edit  Social Science Key to show Icon

- src/components/Markings/components/EditableRect.js
- src/components/Markings/components/MarkableImage.js
- src/components/Markings/components/ShapeEditorSvg.js
- src/components/Markings/components/SvgOverlay.js
- src/utils/__tests__/shape-utils-test.js
- src/utils/shapeUtils.js
Fixes #301
Right now, when using the drawing tools, if your rectangle is too close to the edge, the `x` button will be partially, and sometimes completely, invisible. 
I've added some logic to where: 
- If the button is partially covered by the top of the screen, move it down a bit
- If the button is ever partially covered due to the right of the screen, move the button to the left side of the rect. 
- If the rect is wide enough that the close button can't fit on the either side, move it to the inside left
To make sure , I was sure to create the rects by dragging from a different corner. I also tested on multiple iPhone simulators
I haven't tested android because I think I need permissions that I don't have.  
Due to autoformatting, this PR looks bigger than it actually is. I'd recommend …
> Fix hidden remove buttons

- android/app/build.gradle
- ios/Podfile.lock
- package-lock.json
+ Gifs are not automatically supported on Android in react-native: you have to include a library specifically to support them.
Fixes # 332.
1. Run the Android Emulator (while it is pointing to staging)
2. Go to "Beta Projects"
3. Find the project called "Project with all mobile workflows"
4. Click the "multi answer question" workflow and go through the tutorial. I have the subject set for this workflow set to include gifs!
5. Go through the tutorial, get to the images and ensure that they move!
**This PR is not working if** the images _show up_ but don't _move_.
This was working already, but for peace of mind, please feel free to also try this exact same series of steps on an iOS Simulator to ensure the images move for everybody :)
There's no code here—only a line added to the Android …
> Enable gifs on Android

- package-lock.json
- package.json
- src/components/Markings/DrawingClassifier.js
Fixes https://github.com/zooniverse/mobile/issues/359 (see also: https://zooniverse.slack.com/archives/CM645BF2L/p1611671917008600)
Get accurate image size info from android devices.
- [ x ] Does it work in Android and iOS?
- [ x ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ x ] Are tests passing?
> Get image sizing to work (?) on Android (confirm with Cliff with staging data)

- src/components/classifier/ClassifierButton.js
- src/components/common/SizedMarkdown.js
- src/displayOptions/colorModes.js
+ image size will be limited to 80 points in height and to the width of the container, and will maintain their aspect ratio (so, sized to whichever between width and height hits its limit first)..
+ answer button has some padding such that no markdown image or text runs RIGHT up to the edge of the button and obfuscates its borders
+ markdown button text is vertically centered. None of the options for vertical alignment styling appeared to be doing anything (I  tried several). After a 3 hour time box, I switched to manually pushing text down to the center of the button. The drawback here is that buttons with text that is longer than one line will have all that text in the bottom half of the button. Happy to continue to devote time here, but I recommend only doing it if _a lot_ of our …
> Enable markdown rendering on answer buttons so they can include images

- src/components/projects/ProjectTile.js
Noticed while testing updates. It's helpful to see what this console log is showing - `this.props.project.display_name + " workflows all complete: " + shouldDisplayIsOutOfData.toString()` so I could see good reason to leave this in, in which case feel free to close this. I was about to ask or open a related issue, but it took just as long to open this tiny PR, so here we are!
> Remove console.log from ProjectTile component

- ios/ZooniverseMobile.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
When running the app using XCode I hit an error related to the build system will be deprecated. 
This error can be resolved by changing the following setting within Xcode (bottom left red arrow):
I think updating `ios/ZooniverseMobile.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings` accordingly will automatically enable the setting noted for this project.
This change is not necessary, but might make it easier (one less thing to worry about to get up and running) for other devs to get started.
> Disable build system deprecation error in xcode

- src/utils/__tests__/utils-test.js
- src/utils/workflow-utils.js
Fixes #360.
There's no immediate/live/active issue related to this, but opening for consideration to include in the upcoming release.
Background: invalid drawing task workflows were returning false when validated with the drawing task workflow validation, but then passed to the question task workflow validation which would throw an unhandled error, preventing current and subsequent workflow loading.
- no immediate change to user experience, though #360 was previously preventing workflows from loading, the workflow that caused the issue was manually fixed
- load all valid mobile workflows if a new invalid task workflow is created
- add task type checks in the question task workflow validation, so an invalid drawing or any invalid task type returns false from the question task workflow …
> Add task type checks to isValidQuestionWorkflow and isValidMobileWorkflow tests

- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- ios/Podfile.lock
- package-lock.json
- package.json
- src/components/About.js
- src/components/Discipline.js
- src/components/NotificationModal.js
- src/components/ProjectDisciplines.js
- src/components/Publication.js
- src/components/PublicationList.js
- src/components/Register.js
- src/components/SideDrawerContent.js
- src/components/projects/ProjectList.js
- src/components/projects/ProjectTile.js
- src/components/settings/Settings.js
- src/containers/zooniverseApp.js
Fixes issues running app locally with Android Studio.
- run the app locally with Android Studio (Android Studio Chipmunk | 2021.2.1 Patch 1, node 10)
> Remove Google Analytics and `react-native-google-analytics-bridge`

- android/app/build.gradle
Fixes issue with API 30 and API 31 builds.
API 29 builds previously and continue to work.
Related GitHub issues:
- https://github.com/facebook/SoLoader/issues/55#issuecomment-653890808
- https://github.com/facebook/react-native/issues/25537
- run app on API 30 and API 31 devices
> Fix Android build for API 30 and 31

- src/components/classifier/SwipeCard.js
Fixes issue on iOS with video subjects when click Zooniverse expand button (not iOS fullscreen button), then click iOS minimize button (not Zooniverse "X" button), then on returning to normal classifier the video controls are gone and classifier buttons don't work.
> Refactor SwipeCard to hide SubjectOptionsBar for video subjects on iOS

- package.json
Update package.json scripts to include `react-native`. Current scripts don't run react-native server or react-native builds as expected.
run `npm start` to start react-native local server, `npm android` to build for android, or `npm ios` to build for ios.
> Update package.json scripts

- src/actions/projects.js
- src/components/classifier/Tutorial.js
Disabled museum mode if user is not logged in. This prevents the state where a logged out user clicks on a project and sees 1) no back button 2) generic title 3) different, darker styling. Projects that are marked museum mode will still have these differences if the user is logged in.
> Only tag projects with museum mode if user is logged in.

- .eslintrc.js
Errors were not showing in vscode. For example you could remove an import and no error would show. The parser in the eslintrc.js file needed to be updated to the correct parser. Now vscode will show errors like undefined variables and missing imports.
> Update eslint parser to show errors in code.

- src/actions/projects.js
The goal is to filter out the finished projects so they are not shown.
There were 2 approaches I tried:
1) Call for projects with separate API calls where state=live & state=paused. Pros: by not calling for finished it saved 1 extra api call in total. Cons: By separating the calls, the order of the projects was different than before.
2) Call for all projects and filter out finished. Pros: order stays the same (except for not showing finished projects). Cons: 1 extra api call.
The API calls are called in parallel so there was no performance gain with method 1 so I oped for method 2 to keep the order of projects the same as before.
> Filter out finished projects.

- src/components/NavBar.js
Per conversation https://github.com/zooniverse/mobile/issues/497#issuecomment-1921789366, the zoon icon in the upper left of the navigation header should be taking the user to the home screen.
> Connect zoon icon in nav header to the home screen.

- android/app/build.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- src/components/classifier/FeedbackModal.js
- src/components/classifier/SwipeClassifier.js
This bug was a combination of two separate issues and would've only occurred in museum mode. 
1) There was some code from before the reskinning that was no longer needed and could've been removed. It was comparing the swiper index to the subject list to display the subject. At some point the swiper index got higher than the highest value in the subject list and caused the crash.
2) In the feedback modal is a timeout that dismisses the modal after 10 seconds in museum mode. It was not being cleared when it was finished and would increase the swipe index, causing the swipe index to be higher than the length of the subject list and therefore attempting to call the id on a subject list object that didn't exist.
The fix was to 1) remove the code not needed and 2) clear to the timeout during …
> Clear timeout in modal component. Remove shouldAnimateOverlay.
