zooniverse/mobile

- Project.js
- ProjectList.js
- constants/mobile_projects.js
- index.android.js
- index.ios.js
- ios/ZooniverseMobile/Base.lproj/LaunchScreen.xib
- ios/ZooniverseMobile/Images.xcassets/Contents.json
*  Clean up android js
*  Add constants for the Project list (uses a different list of IDs for production and development)
*  Add new components for the ProjectList and individual Project listing
Closes #5
> Display a list of mobile-friendly projects

- .eslintrc
- Project.js
- ProjectList.js
- index.android.js
- index.ios.js
Add eslint and lint files.  There are still a couple of violations that will be cleaned up - The console errors will be cleaned up with a subsequent branch (add-error-messaging) and the new variables added for styling will be consolidated once react-native-extended-stylesheet is added.
> Add eslint and clean up files

- Project.js
- ProjectList.js
- index.android.js
- index.ios.js
- package.json
- theme.js
Add react-native-extended-stylesheet and convert styling variables to use globally.  Using extended-stylesheet will allow us more control over styling - including adding percentages, media queries, pseudo-classes
> Add extended-stylesheet for more control over styling

- package.json
Add dev dependency for npm eslint packages
> Add eslint to devDependencies

- Project.js
- ProjectList.js
Add popup alert messages when errors occur.  Converts the two using console statements into alerts.
Closes #12
> Convert console errors to alerts

- index.android.js
Missed adding android so the styles weren't displaying properly
> Add compilation of stylesheet to android

- Project.js
- android/app/build.gradle
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/build.gradle
- android/settings.gradle
- constants/globals.js
- index.android.js
- index.ios.js
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- package.json
Implement google analytics on the "Zooniverse Mobile" GA property.  This PR adds tracking of "Home" views and tracking of "View Project" events (with project name as the event action).
To verify this PR works you'll need access to our google analytics - under Zooniverse account -> Zooniverse Mobile -> Real-time  (Laura can give you access if you don't' have it, I can show you how to view the reports.
> Add google-analytics-bridge

- README.md
> Update Readme - Add instructions for Xcode bug and Android setup

- src/actions/index.js
- src/components/ProjectList.js
- src/reducers/index.js
Fixes #45 
Moves the API call from the ProjectList component into redux.
> Move project list api call into redux

- src/components/About.js
- src/components/SideDrawerContent.js
- src/components/StyledText.js
- src/containers/app.js
Add new About screen with the current text from PFE (this may change after feedback)
> Add About screen

- src/actions/index.js
- src/components/Button.js
- src/components/NavBar.js
- src/components/ProjectDisciplines.js
- src/components/SideDrawerContent.js
- src/components/SignIn.js
- src/theme.js
Adds an option on the sign in screen to "Continue without signing in"
*  Adds "isGuestUser" boolean to user in the redux store
*  Update the UI in a couple of places this affects - display "Guest User" rather than the user display name, alter the side drawer to give an option to "Sign In" and remove the "Sign Out" option
*  Move around the order of the buttons on the sign in screen a bit
> Allow users to continue as guest

- android/app/build.gradle
Update pusher-websocket-android to most recent to fix build errors in android
> Update Android Pusher version

- package.json
- src/actions/auth.js
- src/components/Button.js
- src/components/Checkbox.js
- src/components/Input.js
- src/components/Register.js
- src/components/SignIn.js
- src/components/StyledText.js
- src/components/__tests__/Checkbox-test.js
- src/components/__tests__/Register-test.js
- src/components/__tests__/__snapshots__/Checkbox-test.js.snap
- src/components/__tests__/__snapshots__/Input-test.js.snap
- src/components/__tests__/__snapshots__/Register-test.js.snap
- src/components/__tests__/__snapshots__/SignIn-test.js.snap
- src/containers/app.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
- src/theme.js
- src/utils/__tests__/utils-test.js
- src/utils/is-valid-email.js
- src/utils/is-valid-login.js
Adds Register component
Adds Checkbox component
Adds functionality to Input component to accept a label/sub-label, new keyboard style
Add new state for Registration to capture data entry
Add/update theme colors for the Registration button
Adds new tests for Register and Checkbox, and new utils for checking valid email and valid login
Updates snapshots for tests that changed due to updated Input component (SignIn and Input) and reducers test for new Registration initial state
> Add Checkbox Component and Registration

- __mocks__/react-native-svg.js
- android/app/build.gradle
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- package.json
- src/actions/auth.js
- src/actions/user.js
- src/components/CircleRibbon.js
- src/components/NavBar.js
- src/components/UserAvatar.js
- src/components/__tests__/CircleRibbon-test.js
- src/components/__tests__/__snapshots__/CircleRibbon-test.js.snap
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/utils/color-from-string.js
Add react-native-svg package from node for SVG support (RN doesn't have this built in)
Load user project data for use with the Circle Ribbon (user project data will also be used for other pieces)
Add CircleRibbon component to display the ribbon around the user avatar, and update some styles as a result
Add react-native-svg mocks and test for CircleRibbon
Fixes #36
> Add Circle Ribbon SVG

- .travis.yml
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
Also fix the existing failing test on master
> Add travis to run tests

- src/actions/index.js
- src/actions/user.js
- src/components/Discipline.js
- src/components/ProjectDisciplines.js
- src/components/ProjectList.js
- src/components/__tests__/ProjectList-test.js
- src/components/__tests__/__snapshots__/ProjectDiscipline-test.js.snap
Fixes #37 
*  Updates fetchProjectsByParms to allow 'recent' parameter that will take the intersection of projects in the preference list and mobile projects
*  Load these recents once user projects are loaded
*  Add "Recent" option to the Project Disciplines (home screen) list for logged in users
*  Update Discipline component to allow Font Awesome icon, since this doesn't use the ZooIcon
*  Update ProjectList component to display a message if it's empty
*  Update tests
> Add Recents

- src/components/ProjectDisciplines.js
- src/components/__tests__/__snapshots__/ProjectDiscipline-test.js.snap
Fixes #38 
*  Add total classification to ProjectDisciplines (home screen)
*  Update test
> Add total classification statistic

- src/actions/session.js
- src/components/__tests__/Checkbox-test.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
- src/utils/session.js
*  Session wasn't being stored when newly generated
*  Session wasn't being initialized in the reducers
*  Interpolation was incorrect
> Fix issues with session

- src/actions/classifier.js
- src/actions/index.js
- src/actions/user.js
- src/components/CircleRibbon.js
- src/components/ClassificationPanel.js
- src/components/SizedImage.js
- src/components/SwipeClassifier.js
- src/components/Tutorial.js
- src/components/__tests__/SizedImage-test.js
- src/components/__tests__/SwipeClassifier-test.js
- src/components/__tests__/Tutorial-test.js
- src/components/__tests__/__snapshots__/SizedImage-test.js.snap
- src/components/__tests__/__snapshots__/SwipeClassifier-test.js.snap
- src/components/__tests__/__snapshots__/Tutorial-test.js.snap
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/index.js
- src/theme.js
Adds the Tutorial and supporting items:
*  Sets up the project preferences (for recording tutorial completion) in case the user hasn't visited the project before on the desktop
*  Alters the ActivePreferences to store all projects returned in redux, and then changes the Recent Projects list and CircleRibbon to filter only active
*  Gets the tutorial and any attached images (media)
*  Marks tutorial as completed.  For guests it will remember that they completed it for that session.
*  Adds a SizedImage component that does animations on images when loaded in the Tutorial.  This helps keep it from being jumpy.
> Add Tutorial to Classification Panel

- src/components/Question.js
- src/components/StyledModal.js
- src/components/SwipeClassifier.js
- src/components/TaskHelp.js
- src/components/__tests__/Question-test.js
- src/components/__tests__/TaskHelp-test.js
- src/components/__tests__/__snapshots__/Question-test.js.snap
- src/components/__tests__/__snapshots__/SwipeClassifier-test.js.snap
- src/components/__tests__/__snapshots__/TaskHelp-test.js.snap
- src/components/__tests__/__snapshots__/WorkflowPrompt-test.js.snap
Add task help to display a question mark icon next to the question.  It opens the task help in a modal.
> Add Task Help

- ios/ZooniverseMobile/Info.plist
Fix a couple of issues that iTunes complains about.
> Fix errors that come up when submitting through iTunes

- .gitignore
- README.md
- package-lock.json
- package.json
- src/containers/app.js
- Add `remote-redux-devtools`
- Add some explanation in the README on how to use the devtools
- Add some vscode stuff to the gitignore so vscode specific configurations don't get committed
> Set up remote-redux-devtools

- src/actions/projects.js
- src/components/ProjectDisciplines.js
- src/components/__tests__/ProjectDiscipline-test.js
- src/components/projects/ProjectTile.js
- src/constants/globals.js
Describe your changes:
I was checking for out of data incorrectly. Instead of checking the workflow completeness I was checking the project completeness. 
Also, added out of data checks for projects with multiple workflows.
> Fix Out of Data Bug

- android/app/build.gradle
- android/app/src/main/java/com/zooniversemobile/MainApplication.java
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- src/actions/projects.js
- src/actions/user.js
- src/components/ProjectDisciplines.js
- src/components/__tests__/__snapshots__/ProjectDiscipline-test.js.snap
- src/reducers/__tests__/projectReducer-test.js
- src/reducers/projectsReducer.js
- src/utils/promiseUtils.js
Addressing #184 
Describe your changes:
- Added pull refresh to the home screen of the app
- Fixed a bug with the google analytics Android dependency
- Some slight refactoring to the projects downloading code
> Add Pull Refresh

- src/actions/auth.js
- src/actions/user.js
- src/components/projects/ProjectTile.js
- src/containers/app.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/userReducer.js
Fixes #193 
There was a really bad bug where after a user registers, the classifier would hang on load. There aren't a lot of changes here, but they are pretty crucial for the app to function correctyly
> Fix register

- src/actions/projects.js
- src/components/Discipline.js
- src/components/ProjectDisciplines.js
- src/components/WebViewScreen.js
- src/components/__tests__/__snapshots__/Discipline-test.js.snap
- src/components/classifier/SwipeClassifier.js
- src/components/projects/ProjectList.js
- src/components/projects/ProjectTile.js
- src/constants/globals.js
- src/reducers/__tests__/__snapshots__/reducers-test.js.snap
- src/reducers/projectsReducer.js
This PR finishes off the beta review Code.
- Add Beta Projects to main projects call
- Add UI for Beta Projects section
- Add redux state for beta projects
>  Beta Part 2 Pull Projects

- src/actions/classifier.js
- src/actions/projects.js
- src/components/FullScreenImage.js
- src/components/ZoomableImage.js
- src/components/__tests__/__snapshots__/ZoomableImage-test.js.snap
- src/components/classifier/Question.js
- src/components/classifier/SwipeClassifier.js
- src/components/classifier/__tests__/SwipeClassifier-test.js
- src/components/classifier/__tests__/__snapshots__/Question-test.js.snap
- src/utils/__tests__/markdownUtils-test.js
- src/utils/markdownUtils.js
The swipe workflow didn't allow any images to show in the question. The pr allows for one image (the image from the question markdown) to be displayed alongside the
> Add images to questions

- src/actions/images.js
- src/actions/projects.js
- src/components/Markings/DrawingClassifier.js
- src/components/Markings/ImageWithSvgOverlay.js
- src/components/ProjectDisciplines.js
- src/components/classifier/ClassifierButton.js
- src/components/classifier/ClassifierContainer.js
- src/components/classifier/NeedHelpButton.js
- src/components/classifier/SwipeCard.js
- src/components/classifier/SwipeClassifier.js
- src/components/classifier/SwipeTabs.js
- src/components/classifier/__tests__/__snapshots__/SwipeTabs-test.js.snap
- src/components/common/ProgressIndicatingImage.js
- src/components/common/SubjectLoadingIndicator.js
- src/components/projects/ProjectTile.js
- src/containers/app.js
- src/navigators/classifierNavigator.js
- src/utils/projectUtils.js
- src/utils/workflow-utils.js
Now that we have designs, I'm going to start committing to master instead of the other branch. 
I'm going to port over some of the stuff that we merged in there in future PRs.
Detailed explanations for the changes are detailed in the commit messages.
- Added a navigator class that handles navigation to classifiers
- Refactor a bunch of components out of SwipeClassifier so they can be used in the drawing classifier.
- Refactor Image Loading logic
- Add DrawingScreen
> Drawing Add Drawing Screen

- android/app/build.gradle
- ios/ZooniverseMobile/Info.plist
Just an update to the app versions numbers.
As well, did some testing for the latest version of xcode and everything seems to be working.
> Update Version string/ Update Xcode

- src/components/Markings/DrawingClassifier.js
- src/components/Markings/components/DrawingHeader.js
- src/components/classifier/Question.js
- src/components/classifier/__tests__/__snapshots__/Question-test.js.snap
The question text for drawing tasks was over lapping with the drawing tool indicator. This PR fixes that 
Invision Mock-ups:  https://projects.invisionapp.com/d/main#/console/15642822/339628085/preview
> Fix Question layout issues

- package-lock.json
- package.json
- src/reducers/__tests__/projectReducer-test.js
- src/reducers/projectsReducer.js
There was an issue with how we select projects to show. Essentially, we weren't showing projects that were both `launch_approved` and `beta_approved`.
> Fix how we select projects to show

- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile.xcodeproj/xcshareddata/xcschemes/ZooniverseMobile_Museum.xcscheme
- ios/ZooniverseMobile/Info.plist
- ios/ZooniverseMobile/ZooniverseMobile.entitlements
- package-lock.json
- src/components/Markings/DrawingClassifier.js
- src/components/Markings/components/DrawingButtons.js
- src/components/Markings/components/ShapeInstructionsView.js
- src/components/StyledModal.js
- src/components/classifier/ClassificationPanel.js
- src/components/classifier/ClassifierButton.js
- src/components/classifier/NeedHelpButton.js
- src/components/classifier/TaskHelpModal.js
- src/components/classifier/Tutorial.js
- src/components/classifier/__tests__/__snapshots__/Question-test.js.snap
- src/components/classifier/__tests__/__snapshots__/Tutorial-test.js.snap
- src/components/common/SizedMarkdown.js
- src/containers/app.js
- src/navigators/classifierNavigator.js
- src/theme.js
Add custom features for a mapping historic skies museum mode. Please not that I made a new branch on the zooniverse/mobile repo that I'm merging this into.
Invision Mock-ups:  https://projects.invisionapp.com/d/main#/console/15642822/339630114/preview
- Update the drawing classifier to have a "dark mode" (see invision)
- Update the drawing classifier to remove any navigation options from the page.
> Museum mode

- android/app/build.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/Info.plist
- src/components/Markings/DrawingClassifier.js
- src/components/StyledMarkdown.js
- src/components/classifier/FieldGuide.js
- src/components/classifier/FieldGuideItemDetail.js
- src/components/classifier/SwipeClassifier.js
- src/components/classifier/__tests__/__snapshots__/FieldGuideItemDetail-test.js.snap
- src/containers/app.js
> Fixes several items in museum mode release (see commit messages)

- android/app/build.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/Info.plist
**Describe your changes**
Just a few edits to increment the versions to ones listed in the app stores.
> Update to Current Store Versions

- .travis.yml
- android/app/build.gradle
- android/sentry.properties
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/sentry.properties
- package-lock.json
- package.json
- src/actions/projects.js
- src/components/ProjectDisciplines.js
- src/components/Workflow.js
- src/containers/app.js
Fixes #322 
Right now, we don't have any info about the cause of issues until and unless we can recreate the issue locally. Some kind of error reporting solution can help us with that, and we're going with Sentry since we already have a Sentry account and already use it to track 6 or 7 other apps for our organization.
+ Here is our brand new Sentry mobile-app project page: https://sentry.io/organizations/zooniverse-27/issues/?project=5371400
+ My thinking was to put the DSN in an environment variable rather than commit it straight to the repo, but the official guidance from Sentry appears to be not to do that: https://forum.sentry.io/t/dsn-private-public/6297
**I have checked the following, but please also check the following:**
**A note on the changes:**
It _looks_ like a lot, but most …
> Add sentry for error logging

- src/components/NotificationModal.js
- src/components/PublicationList.js
- src/components/SizedImage.js
- src/components/ZooWebView.js
Everything in the app should work the same as it did before. These were changes related to getting ahead of deprecations in react native.
1. We have several warnings in our app for things that are going to be deprecated. This PR fixes some of those!
> Inspect warnings

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- ios/ZooniverseMobile.xcodeproj/project.pbxproj
- ios/ZooniverseMobile/Info.plist
- package-lock.json
- package.json
- src/components/projects/ProjectList.js
Fixes # .
Build the application! We had some dependency updates to make to get a successful build for release. 
Invision Mock-ups:
> Fix android dependencies

- src/actions/auth.js
Fixes [this card](https://github.com/zooniverse/mobile/projects/7#card-70349360).
> Remove extra space added by autofill to usernames during login

- ios/ZooniverseMobile.xcodeproj/project.pbxproj
Per https://github.com/zooniverse/mobile/pull/403#discussion_r914121838
- removes some comments related to the removed dependency Google Analytics Bridge (#402)
> Remove GoogleAnalyticsBridge comments in project.pbxproj

- android/app/build.gradle
- android/gradle.properties
Fixes crash on open, build issues.
- open app
> Updates per Android release 2.9.1

- android/app/build.gradle
- android/gradle.properties
- ios/ZooniverseMobile/Info.plist
Fixes issue with typed text not showing (i.e. in username and password inputs).
> Set app in light mode

- android/app/build.gradle
- android/gradle.properties
- src/components/FullScreenMedia.js
- src/components/ZoomableImage.js
Fixes issue on Android and iOS with images not showing in full screen mode.
> Refactor ZoomableImage uri property

- android/app/build.gradle
- android/gradle.properties
- src/components/FullScreenMedia.js
- src/components/ZoomableImage.js
- src/components/classifier/SwipeableSubject.js
Fixes Android issue with video subjects not expanding in full screen mode.
> Add resizeMode contain for full screen and swipeable video subject

- src/components/classifier/MultiAnswerClassifier.js
- src/components/classifier/SwipeCard.js
Add video player for video subjects within MultiAnswerClassifier
> Add video subjects for MultiAnswerClassifier
